# Generated by Django 5.2.8 on 2026-05-21 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("reservations_connect", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UrnikClassroom",
            fields=[
                (
                    "foreignreservable_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="reservations_connect.foreignreservable",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
            bases=("reservations_connect.foreignreservable",),
        ),
        migrations.CreateModel(
            name="UrnikTeacher",
            fields=[
                (
                    "foreignreservable_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="reservations_connect.foreignreservable",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
            bases=("reservations_connect.foreignreservable",),
        ),
    ]
