# Generated by Django 5.2.8 on 2026-10-01 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fri_urnik", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="urnikclassroom",
            name="foreign_id",
            field=models.PositiveBigIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="urnikteacher",
            name="foreign_id",
            field=models.PositiveBigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
