# Generated by Django 5.2.8 on 2026-07-07 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("reservations_connect", "0004_delete_metronikroom"),
    ]

    operations = [
        migrations.CreateModel(
            name="MetronikRoom",
            fields=[
                (
                    "foreignreservable_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="reservations_connect.foreignreservable",
                    ),
                ),
                (
                    "arhitektura",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                (
                    "tehnologija",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                ("opis", models.CharField(blank=True, max_length=256, null=True)),
                (
                    "stevilka_sist_kljuca",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                (
                    "oznake_sist_kljuca",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                (
                    "oznaka_prostora",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                (
                    "oznake_na_vratih",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                (
                    "table_v_objektu",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                ("etaza", models.CharField(blank=True, max_length=256, null=True)),
                (
                    "zap_st_prostora",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
            ],
            bases=("reservations_connect.foreignreservable",),
        ),
    ]
