# Generated by Django 5.2.8 on 2026-02-18 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservations', '0008_alter_nrequirements_options_alter_nresources_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForeignReservable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.reservable')),
            ],
        ),
        migrations.CreateModel(
            name='FriprosvetaActivity',
            fields=[
                ('foreignreservable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reservations_connect.foreignreservable')),
                ('foreign_id', models.IntegerField()),
            ],
            bases=('reservations_connect.foreignreservable',),
        ),
        migrations.CreateModel(
            name='FriprosvetaTeacher',
            fields=[
                ('foreignreservable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reservations_connect.foreignreservable')),
                ('foreign_id', models.IntegerField()),
            ],
            bases=('reservations_connect.foreignreservable',),
        ),
        migrations.CreateModel(
            name='TimetableClassroom',
            fields=[
                ('foreignreservable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reservations_connect.foreignreservable')),
                ('foreign_id', models.IntegerField()),
            ],
            bases=('reservations_connect.foreignreservable',),
        ),
        migrations.CreateModel(
            name='TimetableGroup',
            fields=[
                ('foreignreservable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reservations_connect.foreignreservable')),
                ('foreign_id', models.IntegerField()),
            ],
            bases=('reservations_connect.foreignreservable',),
        ),
        migrations.CreateModel(
            name='WiseActivity',
            fields=[
                ('foreignreservable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reservations_connect.foreignreservable')),
                ('name', models.CharField(max_length=255)),
                ('vrsta', models.CharField(max_length=255)),
            ],
            bases=('reservations_connect.foreignreservable',),
        ),
        migrations.CreateModel(
            name='WiseIzvajalec',
            fields=[
                ('foreignreservable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reservations_connect.foreignreservable')),
                ('name', models.CharField(max_length=255)),
            ],
            bases=('reservations_connect.foreignreservable',),
        ),
        migrations.CreateModel(
            name='WiseProstor',
            fields=[
                ('foreignreservable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reservations_connect.foreignreservable')),
                ('name', models.CharField(max_length=255)),
            ],
            bases=('reservations_connect.foreignreservable',),
        ),
        migrations.CreateModel(
            name='WiseSkupina',
            fields=[
                ('foreignreservable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reservations_connect.foreignreservable')),
                ('name', models.CharField(max_length=255)),
            ],
            bases=('reservations_connect.foreignreservable',),
        ),
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('source', models.TextField()),
                ('created_reservables', models.ManyToManyField(related_name='created_by_import', to='reservations_connect.foreignreservable')),
                ('reservations', models.ManyToManyField(to='reservations.reservation')),
                ('updated_reservables', models.ManyToManyField(related_name='modified_by_import', to='reservations_connect.foreignreservable')),
            ],
        ),
        migrations.CreateModel(
            name='MetronikRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arhitektura', models.CharField(blank=True, max_length=256, null=True)),
                ('tehnologija', models.CharField(blank=True, max_length=256, null=True)),
                ('opis', models.CharField(blank=True, max_length=256, null=True)),
                ('stevilka_sist_kljuca', models.CharField(blank=True, max_length=256, null=True)),
                ('oznake_sist_kljuca', models.CharField(blank=True, max_length=256, null=True)),
                ('oznaka_prostora', models.CharField(blank=True, max_length=256, null=True)),
                ('oznake_na_vratih', models.CharField(blank=True, max_length=256, null=True)),
                ('table_v_objektu', models.CharField(blank=True, max_length=256, null=True)),
                ('etaza', models.CharField(blank=True, max_length=256, null=True)),
                ('zap_st_prostora', models.CharField(blank=True, max_length=256, null=True)),
                ('reservable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reservations.reservable')),
            ],
        ),
    ]
