# Generated by Django 5.2.8 on 2026-05-21 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reservations_connect", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="friprosvetateacher",
            name="foreignreservable_ptr",
        ),
        migrations.RemoveField(
            model_name="timetableclassroom",
            name="foreignreservable_ptr",
        ),
        migrations.RemoveField(
            model_name="timetablegroup",
            name="foreignreservable_ptr",
        ),
        migrations.DeleteModel(
            name="FriprosvetaActivity",
        ),
        migrations.DeleteModel(
            name="FriprosvetaTeacher",
        ),
        migrations.DeleteModel(
            name="TimetableClassroom",
        ),
        migrations.DeleteModel(
            name="TimetableGroup",
        ),
    ]
