# Generated by Django 5.2.8 on 2026-05-21 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "reservations_connect",
            "0002_remove_friprosvetateacher_foreignreservable_ptr_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wiseizvajalec",
            name="foreignreservable_ptr",
        ),
        migrations.RemoveField(
            model_name="wiseprostor",
            name="foreignreservable_ptr",
        ),
        migrations.RemoveField(
            model_name="wiseskupina",
            name="foreignreservable_ptr",
        ),
        migrations.DeleteModel(
            name="WiseActivity",
        ),
        migrations.DeleteModel(
            name="WiseIzvajalec",
        ),
        migrations.DeleteModel(
            name="WiseProstor",
        ),
        migrations.DeleteModel(
            name="WiseSkupina",
        ),
    ]
