# Generated by Django 5.2.8 on 2026-07-07 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "reservations_connect",
            "0003_remove_wiseizvajalec_foreignreservable_ptr_and_more",
        ),
    ]

    operations = [
        migrations.DeleteModel(
            name="MetronikRoom",
        ),
    ]
